# Generated by Django 2.2.3 on 2019-08-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_forum_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='body',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
