# Generated by Django 2.2.3 on 2019-07-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('shortcut', models.SlugField(verbose_name='atalho')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('image', models.ImageField(upload_to='courses/images', verbose_name='Image')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
        ),
    ]
