"""
Django settings for fcsSimpleMooc project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/

Issues:

    . initial commint and deployment resulted in no CSS renderization
    . problem with SSH-keys (resolved)
    .
    .
    
"""
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
#
#from django.conf.settings import TEMPLATE_CONTEXT_PROCESSORS as TCP
#
import dj_database_url

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u8z5#+i)&dg!!co_u=ht#6@nt3)r17iqi8f3-7oox3c(z!ii&('

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # libraries (libs)
    'taggit',
    # custom apps
    'fcsSimpleMooc.core',
    'fcsSimpleMooc.courses',
    'fcsSimpleMooc.accounts',
    'fcsSimpleMooc.forum',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#
#                            DEPRECATED
#
# from  django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS
# TEMPLATE_CONTEXT_PROCESSORS = TCP + ('django.core.context_processors.request',)

ROOT_URLCONF = 'fcsSimpleMooc.urls'

WSGI_APPLICATION = 'fcsSimpleMooc.wsgi.application'

# for 
SITE_ID = 2

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
#
#    DATABASES configuration transfered to local_settings.py
#

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us' # can change to "pt-br"

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'fcsSimpleMooc', 'media')
MEDIA_URL = '/media/'

#                           E-mails
# Development with true dispatch
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Devellopment   without sending 
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'info@csadesign.eco.br'
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'info@csadesign.eco.br'
EMAIL_HOST_PASSWORD = '245353f10@I!'
EMAIL_HOST = 'mail.csadesign.eco.br'
EMAIL_PORT = 587 # was 465

# e-mail from csadesign.eco.br
CONTACT_EMAIL = 'info@csadesign.eco.br'

# URLs for Django auth system
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_URL = 'accounts:logout'
LOGOUT_REDIRECT_URL = 'core:home'
AUTH_USER_MODEL = 'accounts.User'

# Heroku settings
# from import dj_database_url

DATABASES = {'default': dj_database_url.config(),}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#Allow all host headers
ALLOWED_HOSTS = ['*']

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

#  Add configuration for static files storage using whitenoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Not used, as static files are inside "/core/" directory
# STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

# importing local settings in order to run application locally
try:
    from fcsSimpleMooc.local_settings import *
except ImportError:
    pass
##########                  END                ###########